 <tr>
    <td>%pid%</td>
    <td>%title%</td>
    <td>%category%</td>
    <td>%subcategory%</td>
    <td>%brand%</td>
    <td>%price%</td>
    <td>%qty%</td>
    <td>%size%</td>
    <td>%color%</td>
    <td>%shortdescription%</td>
    <td>%specification%</td>
    <td>%additionalinfo%</td>
</tr>